### ISSUE TITLE
About dilation convolution

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [octiapp/KerasPersonLab#13]
It seems like that no dilation convolution in origin PersonLab paper, according to classical Resnet .
Did I miss or ignore something important in paper?

**Comment by jricheimer** [comment]
Hi @MoonBunnyZZZ . Thanks for your interest. See section 4.1 in the paper:

"Our ResNet CNN network backbones have nominal output stride (i.e., ratio of the input image to output activations size) equal to 32 but we reduce it to 16 during training
and 8 during evaluation using atrous convolution."

They cite their Deeplab paper there for more details on this.
