### ISSUE TITLE
TypeError: 'KeysView' object does not support indexing

### ISSUE THREAD

**Issue by miibotree** [octiapp/KerasPersonLab#3]
when I use python 3, I get the following Error:
TypeError: 'KeysView' object does not support indexing
so when use python 3, I should modify the function data_gen() in tf_data_generator.py in line87:
key = root.keys()
to
key = list(root.keys())
and now key could be iterated.
I think you should tell the environment detail in README so that other people could avoid such mistakes

**Comment by jricheimer** [comment]
Thanks @miibotree!

I will definitely add my environment details that this was run with to the README. Please post any more issues you come across.
