### ISSUE TITLE
Error when training!

### ISSUE THREAD

**Issue by Minotaur-CN** [octiapp/KerasPersonLab#8]
hi，all
One error happens when training from scratch.

----

KerasPersonLab-updated_model_def/data_prep.py", line 16, in get_ground_truth

    assert(instance_masks.shape[-1] == len(all_keypoints)), '{} != {}'.format(instance_masks.shape[-1], len(all_keypoints))

AssertionError: 7 != 8

**Comment by nitzankoll** [comment]
+1

**Comment by jricheimer** [comment]
Hello @Minotaur-CN @nitzan1207 
The cause of this error was a COCO segm annotation with zero area. I updated the `generate_hdf5` script to handle this, so you will need to delete your current hdf5 file and re-run the script again.
